sudo: false
language: python
python:
- '2.6'
- '2.7'
install:
- pip install requests
- pip install nose
- pip install pep8
- pip install dicttoxml
script:
- pep8 --max-line-length=180 qcloud_cos/.
- nosetests -s -v
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dt3310321
  password: RnG199352433
  on:
    tags: true
    branch: master
